### ISSUE TITLE
[Bug]: Crash on wake up from sleep

### ISSUE THREAD

**Issue by yusufades** [httptoolkit/httptoolkit#647]
### Has this been reported before?

- [X] I have checked for existing reports of this issue

### Repro steps

1. Open desktop app
2. put computer to sleep
3. Wake computer up
4. app has crashed

### How often does this bug happen?

Every time

has been occuring every time for the last few days. did not use to occur before

### The desktop OS you're using

Windows 11

### Error screenshot

![image](https://github.com/user-attachments/assets/bef20c45-299c-4c9c-96b5-d01278fa03a8)

### Any other info?

`last-run.log`
```txt
--- Launching HTTP Toolkit desktop v1.19.0 ---
INFO: Initialising UI (version dea838d340dff67ea7454095f94a28dd681c0110)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
Config checked in 6 ms
Certificates setup in 4 ms
Standalone server started in 4 ms
Server started in 11 ms
Total startup took 25 ms
(node:10024) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
WARN: Third-party cookie will be blocked. Learn more in the Issues tab.
Mock session started, http on port 8000, webrtc enabled
Created docker-tunnel-proxy-8000
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8000
INFO: Proxy store initialized (server version 1.19.1)
Detected terminal command: C:/Program Files/git/git-bash.exe
Usbmux iOS scanning failed: 
INFO: Rules store initialized
INFO: Events store initialized
INFO: Send store initialized
Webextension installed at C:\Users\Yusuf\AppData\Local\Temp\httptoolkit-webextension
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.1
(node:10024) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Browser cache updated
INFO: Service worker loaded
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.1
INFO: Previous server version was 1.19.1
WARN: Admin client stream unexpectedly disconnected [object CloseEvent]
INFO: Admin client stream error [object Event]
WARN: Admin client stream reconnection failed, shutting down: undefined
INFO: Reporting error: Error: Client reconnect error [object Object]
```

**Comment by nutterthanos** [comment]
According to @pimterry this is an temporarily feature not an bug because putting http toolkit to sleep broke just one thing tho and that was mock rules as such hence why this was added
Once root cause of that could be worked out then this wouldn't happen ever again

**Comment by pimterry** [comment]
> this is an temporarily feature not an bug because putting http toolkit to sleep broke just one thing tho and that was mock rules as such hence why this was added

I'm not sure if I'd call it a feature, but yes it's the result of changes to fix #345 and #74. Previously when the connection broke, the app seemed to keep working (but was actually failing and not showing data or handling some requests) until you saved a rule and then it crashed fully and you lost all your rules.

Now, when the connection fails the app tells you and exits immediately. That's a bit better (you don't lose your rules, you don't get confusing partially-broken behaviour) but obviously it's still not good - the app shouldn't crash!

This is now the top of my TODO list though, so I'm going to put a bunch more time into working out how to reproduce this myself and fix it for good this week. My current setup doesn't reproduce the issue, but I've got a new spare machine I'm going to reinstall Windows on in various different versions & configurations until I can hit this reliably myself. Watch this space :eyes:

**Comment by pimterry** [comment]
This is now fixed!

HTTP Toolkit will update in the background the next time you open it, and the following time the fix will take effect. In the new version, it now successfully reconnects and resumes after windows hibernation on affected machines, so this error generally shouldn't ever appear in normal usage. Thanks for the reports and info everybody :+1:

If you still see issues with sleeping after HTTP Toolkit has updated please report it here and I can investigate further. If you run into this error message for other reasons (the server crashing/disconnecting in other exciting new ways) then please open a new issue with more details.

**Comment by xKiian** [comment]
welp! apparently this is not fully fixed.

```
--- Launching HTTP Toolkit desktop v1.19.1 ---
INFO: Initialising UI (version acb7d2a1bc5cda9baadd5186bfa68248277d3f71)
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
INFO: API store initialized
WARN: Third-party cookie will be blocked. Learn more in the Issues tab.
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
INFO: Server initialization failed TypeError: Failed to fetch
Config checked in 45 ms
Certificates setup in 25 ms
Standalone server started in 7 ms
Server started in 15 ms
Total startup took 92 ms
INFO: Service worker loaded
(node:20672) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
Mock session started, http on port 8050, webrtc enabled
Created docker-tunnel-proxy-8050
Docker not available: connect ENOENT //./pipe/docker_engine
INFO: Server started
INFO: Config loaded
INFO: Server started on port 8050
INFO: Proxy store initialized (server version 1.19.3)
httptoolkit-server: Updating CLI... fetching manifest
INFO: Rules store initialized
INFO: Events store initialized
INFO: Send store initialized
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
Webextension installed at C:\Users\redacted\AppData\Local\Temp\httptoolkit-webextension
Detected terminal command: C:/Program Files/git/git-bash.exe
Usbmux iOS scanning failed: 
INFO: Interceptor store initialized
INFO: App started, rendering
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
(node:20672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Browser cache updated
INFO: Previous server version was 1.19.3
Created TensorFlow Lite XNNPACK delegate for CPU.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#-1 is a dynamic-sized tensor).
Failed to handle request: socket hang up
Failed to handle request: socket hang up
Failed to handle request: socket hang up
Failed to handle request: socket hang up
Failed to handle request: socket hang up
Failed to handle request: socket hang up
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
Failed to handle request: socket hang up
[364:11712:0130/175210.735:ERROR:interface_endpoint_client.cc(725)] Message 1 rejected by interface blink.mojom.WidgetHost
WARN: Element resized, but no ref available
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
[364:11712:0130/180258.171:ERROR:device_event_log_impl.cc(201)] [18:02:58.168] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
Failed to handle request: socket hang up
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
WARN: Element resized, but no ref available
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
[364:11712:0130/190053.191:ERROR:device_event_log_impl.cc(201)] [19:00:53.190] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Failed to handle request: socket hang up
Failed to handle request: socket hang up
Failed to handle request: socket hang up
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
Failed to handle request: socket hang up
Failed to handle request: aborted
WARN: Element resized, but no ref available
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
httptoolkit-server: Updating CLI... fetching manifest
httptoolkit-server: Updating CLI... already on latest version: 1.19.3
WARN: Admin client stream unexpectedly disconnected [object CloseEvent]
INFO: Admin client stream error [object Event]
INFO: Admin client stream error [object Event]
INFO: Admin client subscription error [object Event]
INFO: Admin client subscription error [object Event]
INFO: Admin client stream error [object Event]
ERROR: Uncaught (in promise) Error: API error during GET /interceptors: fetch failed with 'Failed to fetch'
INFO: Admin client subscription error [object Event]
INFO: Admin client stream error [object Event]
INFO: Admin client subscription error [object Event]
INFO: Admin client stream error [object Event]
INFO: Reporting error: TypeError: Failed to fetch [object Object]
INFO: Admin client subscription error [object Event]
INFO: Error: API error during POST /update: fetch failed with 'Failed to fetch'
INFO: TypeError: Failed to update a ServiceWorker for scope ('https://app.httptoolkit.tech/') with script ('https://app.httptoolkit.tech/ui-update-worker.js'): An unknown error occurred when fetching the script.
ERROR: Uncaught (in promise) Error: API error during GET /interceptors: fetch failed with 'Failed to fetch'
INFO: Admin client stream error [object Event]
WARN: Admin client stream reconnection failed, shutting down: undefined
INFO: Reporting error: Error: Client reconnect error [object Object]
[364:11712:0130/195754.499:ERROR:device_event_log_impl.cc(201)] [19:57:54.499] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
WARN: Client stopping due to admin server shutdown
Removed docker-tunnel-proxy-8050
Websocket request for unrecognized mock session: befc627a-3c18-42c9-9293-656775e4d47f
Shutting down after API call...
Uninstalling webextension from C:\Users\redacted\AppData\Local\Temp\httptoolkit-webextension
```

i had a fresh chrome instance running for about 1hour and then put my pc to sleep. When coming back i got the same problem as the initial issue. Hope the log helps.

**Comment by pimterry** [comment]
Ah sorry to hear that @xKiian! Is this something that happens frequently on this machine, or was it just a one-off? It's hard to know for sure what could cause this and there's no major clues in the logs there I think. If you manage to find a way to trigger this consistently or you have any clues why it might happen in this case that would be really interesting.

**Comment by xKiian** [comment]
I tried to recreate it but with no luck... I'll keep you updated when it happens the next time

**Comment by BaerMitUmlaut** [comment]
@pimterry This happens quite reliably for me. I use hibernate to turn off my PC and turn it back on the next morning.

**Comment by henxdl** [comment]
@pimterry This happens very reliably for me every time without fail. I always hibernate my PC, and I don't know how to restore the old data. When this error comes up, I usually am not actively using the software, but am looking at logs I captured a while ago. Maybe there could be an option to ignore and just remove the functionality of active capture until restart but allow the user to view logs?

**Comment by nutterthanos** [comment]
> Ah sorry to hear that @xKiian! Is this something that happens frequently on this machine, or was it just a one-off? It's hard to know for sure what could cause this and there's no major clues in the logs there I think. If you manage to find a way to trigger this consistently or you have any clues why it might happen in this case that would be really interesting.

Note how it said INFO: TypeError: Failed to update a ServiceWorker for scope ('https://app.httptoolkit.tech/') with script ('https://app.httptoolkit.tech/ui-update-worker.js'): An unknown error occurred when fetching the script.

Surely that wasen't what broke it

But being that it said failed on /update too would that mean httptoolkit-server crashed or mockttp?

Possibly now it's just the network hasn't come back online yet after waking from hibernation or is it trying to reconnect admin stream too quick after waking?

**Comment by pimterry** [comment]
This has now been significantly improved, with better retry logic and a new UX that doesn't block access to the rest of the UI in the meantime (although you will almost certainly find that some things are broken). Instead of the blocking alert, you'll now see this floating warning in the corner:

<img width="444" height="464" alt="Image" src="https://github.com/user-attachments/assets/38b9a901-c02c-4ac3-b4cc-0ef871961938" />

To update to this fix, you'll need to launch HTTP Toolkit, wait a minute or two for it to update in the background, then restart it.

I'm hopeful this _might_ improve the automatic retry enough that the issue is now self-fixing, but at a minimum this will make it easier to avoid losing your data when this breaks.

I'm reopening this issue in the meantime though to look into it further. For people who can reproduce this, it would be very helpful to know if this fix helps. Most importantly: if you trigger this error, does it eventually recover? Or does it just stay broken forever? I'm hoping that hibernation just makes some connections very slow to recover in these cases, so the previous logic was timing out and extending the retry process means it'll now eventually fix itself given more time 🤞

**Comment by nutterthanos** [comment]
Strangely it's not happening anymore on the latest version now
