### ISSUE TITLE
[Bug]: Response Body Images Broken, Not Showing Images

### ISSUE THREAD

**Issue by dandyraka** [httptoolkit/httptoolkit#825]
### Has this been reported before?

- [x] I have checked for existing reports of this issue

### Repro steps

<img width="1695" height="959" alt="Image" src="https://github.com/user-attachments/assets/5a361547-201a-431b-a80d-a4a548d74d56" />

<img width="730" height="662" alt="Image" src="https://github.com/user-attachments/assets/95917462-2e4f-4417-82f6-06e0ca0122fb" />

### How often does this bug happen?

Every time

### The desktop OS you're using

Windows 11

**Comment by pimterry** [comment]
This is a bug that was briefly live in an update last week, but is now fixed everywhere as far as I'm aware. Your HTTP Toolkit has probably already updated in the background, so if you fully close & relaunch it everything should work correctly. Can you check that and let me know if it fixes the issue?

**Comment by dandyraka** [comment]
This problem still occurs to me, I have done a reinstall but it still doesn't work.

**Comment by pimterry** [comment]
Ok, I've just pushed a further fix, hopefully it should be fully fully resolved now. Next time you launch the app it'll update in the background within a minute or so, the following time the fix will take effect.

You can check the version by hovering your mouse over the HTTP Toolkit logo - it should show UI version `7f795b5` once it's up to date. Does that work for you?

**Comment by dandyraka** [comment]
UI ver: 7f795b5 
Desktop & server ver: 1.24.0

Still doesn't work idk why 

<img width="1590" height="981" alt="Image" src="https://github.com/user-attachments/assets/4bd5fe39-8c43-44e4-9fab-cd7b36fb1d1d" />

**Comment by pimterry** [comment]
That's very strange indeed. The error here is saying that the CSP has `img-src * 'data:'` when it should have `img-src * data:` (no quotes). That makes sense, but that's just been fixed [here](https://github.com/httptoolkit/httptoolkit-ui/commit/7f795b5) in that 7f795b5 commit. Those quotes definitely aren't present in the current live system, and it does now work correctly, I've just done a full reset & check myself. Very odd!

If you go to View and 'Force Reload', does that help? Maybe somehow this is being cached unexpectedly.

If that doesn't help, can you please: open the Network tab of the dev tools there, force reload, and then right click the rows and select "Save all as HAR" to export the traffic, and share that here? That might have some clues.

**Comment by dandyraka** [comment]
It works by Force Reload, thank you so much 😁

**Comment by pimterry** [comment]
Great! Thanks for reporting this, and for the quick responses to help get it sorted :smile:
